name = input("Введите имя :")
surname = input("Введите фамилию :")
age =int (input("Введите возраст :"))
print("Привет ", name, surname, "Тебе ", age)
print("Меня зовут Дима и я твой новый студент ))))")